nuxt/test-utils

- .eslintignore
- lib/generate-port.js
- lib/nuxt.js
- package.json
- types/index.d.ts
- yarn.lock
I wrote some shims in order to be able to use this module with TS and thought it might be nice to have native support for that.
I also took the liberty to update dependencies to use `request-promise` in lieu of the deprecated `request-promise-native`, and to remove the unused dependency `request`.
> Add Types for typescript support

- package.json
> fix(types): include types in published package

- package.json
- src/server.ts
- test/basic.test.ts
- yarn.lock
> feat: request helper

- src/browser.ts
> feat: ensure puppeteer is installed

- src/jest.matchers.ts
- test/basic.test.ts
> chore: rename jest matchers

- src/context.ts
- src/nuxt.ts
- test/__snapshots__/context.test.ts.snap
- test/basic.test.ts
> fix: use random `buildDir` to avoid conflicts

- src/assertions.ts
> feat: add negative assertions

- docs/content/settings.json
`url` : https://github.com/nuxt-community/module-test-utils → https://test-utils.nuxtjs.org
`github` : `nuxt-community/module-test-utils` → `nuxt/test-utils`
`twitter`: `nuxt_js`
Properties order (`create-nuxt-content-docs`)  :
https://github.com/nuxt/content/blob/dev/packages/create-nuxt-content-docs/template/content/settings.json
> docs: update links

- README.md
- docs/content/en/api-reference/browser-testing.md
- docs/content/en/api-reference/buid-setup.md
- docs/content/en/api-reference/expect.md
- docs/content/en/examples/browser.md
- docs/content/en/examples/usage.md
- docs/content/en/index.md
1. Fix typo in Features
2. Update README.md with banner of module.
3. Add API Reference section for docs
> chore(docs): update docs and fix typo

- README.md
Currently preview image is broken because of wrong extension
> docs: fix nuxt/test-utils preview on README

- docs/nuxt.config.js
- docs/package.json
- docs/yarn.lock
Migration to new beautiful docus documentation ❤️
> docs: migration to docus

- src/server.ts
Respect `server.port` configuration, set in `setupTest` or `nuxt.config.js`
eg. 
```js
import { setupTest  } from '@nuxt/test-utils'
const port = 3456
setupTest({
browser: true,
config: {
server: {
port
}
}
})
```
> fix(server): try to use `config.server.port`

- docs/content/en/api-reference/module-testing.md
- docs/content/en/examples/module.md
- src/assertions.ts
- test/unit/generate.test.ts
Add generated assertions, eg:
```js
test('should file generated', () => {
expectFileToBeGenerated('index.html')
})
```
> feat: add generated assertions

- src/context.ts
Some definitions were not in context
Resolve #104
> fix(types): add more type definitions to nuxt interface

- docs/content/en/index.md
Based upon:
https://github.com/nuxt/test-utils/issues/111
@mrazauskas 
Resolves #111
> docs: clarification between nuxt and components testing

- package.json
- src/context.ts
- src/server.ts
- yarn.lock
Use `listhen` instead of `nuxt.listen`
> feat: use listhen

- package.json
- src/server.ts
- test/unit/module.test.ts
- yarn.lock
Use `ohmyfetch` instead of `got`
The result of `ohmyfetch` is different of `got`
```js
// ohmyfetch
const html = await get('/')
expect(html).toContain('Works!')
// got
const { body } = await get('/')
expect(body).toContain('Works!')
```
> feat!: use ohmyfetch

- examples/app-vitest-full/tests/nuxt/index.spec.ts
- src/runtime-utils/mount.ts
resolves https://github.com/nuxt/test-utils/issues/525
> fix(runtime-utils): don't stub helpers when `shallow`

- examples/app-vitest-full/components/BoundAttrs.vue
- examples/app-vitest-full/components/InjectedValueComponent.vue
- examples/app-vitest-full/plugins/inject-value.ts
- examples/app-vitest-full/tests/nuxt/injected-value-component.spec.ts
resolves https://github.com/nuxt/test-utils/issues/539
> test: add example test for nuxt-injected value

- src/core/browser.ts
also by default waits for hydration when calling `createPage`
resolves https://github.com/nuxt/test-utils/issues/649
> feat(e2e): add `'route'` and `'hydration'` options for `page.goto()`

- src/core/types.ts
N/A
Add block comments to allow intellisense to provide contextual info.
> chore: provide intellisense hints on setup properties

- src/runtime-utils/render.ts
close: https://github.com/nuxt/test-utils/issues/1219
This fixes a Vue warning that occurs when using renderSuspended:
```
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
The warning was caused by passing the Suspense component as a child node to WrapperComponent instead of passing it as a default slot function. Vue 3 expects all slots to be passed as functions for better performance and correctness.
```
This change wraps the Suspense vnode in a function and passes it to the WrapperComponent as a proper default slot.
> fix: wrap WrapperComponent default slot in function
