- lib/setup.js
- package.json
- test/setup.test.js
- yarn.lock
`loadConfig` with `merge=false` was using spread operator to
clone  properties from fixture's configuration. Since that is
a shallow copy, child objects were returned by reference and
allowed caller to mutate those objects, affecting further
uses of `loadConfig`. Ensure that is not possible by returning
a copy of loaded config.
This was a problem when one test loaded config and passed it
to Nuxt Builder. Nuxt builder then appended generated plugins
to plugins object and those plugins were then used by subsequent
tests, even if it intended to build new, clean fixture.
> fix: don't allow mutating original config object by the caller

- types/index.d.ts
"Options" type was not correct since it expands to "request.UriOptions & RequestPromiseOptions"
which means that it requires "uri" or "url" property while this "get" API requires "uri" separately.
Use just "RequestPromiseOptions" for the options.
> fix(types): correct types of get method options

- docs/content/en/examples/module.md
Into the nuxt module example, it miss the import of `expectModuleToBeCalledWith`
> docs(example): add missing `expectModuleToBeCalledWith` in example

- package.json
- yarn.lock
Whenever we start a project/module and use `@nuxt/test-utils` with its preset, there is a dependency error `@babel/preset-typescript`
This PR adds this dependency
> fix: add missing @babel/preset-typescript dependency

- src/context.ts
- test/unit/__snapshots__/context.test.ts.snap
With `loadNuxtConfig` detect `nuxt.config.js` or `nuxt.config.ts` from https://github.com/nuxt/nuxt.js/blob/dev/packages/config/src/load.js#L11
Resolve #100
> fix: detect `nuxt.config` with different extensions

- src/nuxt.ts
> feat: resolve rootDir

- docs/content/en/api-reference/module-testing.md
- docs/content/en/examples/module.md
updates example tests so they'll work out of the box with windows path separators
closes #113
> docs: update with windows-compatible example test

- docs/content/en/api-reference/module-testing.md
- src/assertions.ts
Included the `addModule` option in the [module testing page](https://test-utils.nuxtjs.org/api-reference/module-testing)
fixes #119
> fix: add missing method types for moduleContainer

- test/e2e/browser.test.ts
- test/fixtures/basic/nuxt.config.js
- test/fixtures/consola/nuxt.config.js
- test/unit/generate.test.ts
- test/unit/module.test.ts
Removed unnecessary code in test and fixture files.
For those who look for usage inside `test` folder, it will be easier to read and to understand how all works.
> test: clean up

- docs/content/en/api-reference/setup.md
- src/context.ts
Value of the `buildDir` option was never read. It was only included in typings and documentation.
I think it is better to remove it and simplify public API . Seems like there was no need for it.
Couple of days ago I was trying to play with it. Config overrides was perfect solution (also works for `generate.dir`).
> chore: remove `buildDir` option in favor of `config.buildDir`

- docs/content/en/api-reference/setup.md
After #105 got merged, one can use either `nuxt.config.js` or `nuxt.config.ts` by default.
Alternately we could write: `nuxt.config.[jt]s`. Less verbose.
> docs: fix `configFile` default

- src/assertions.ts
- src/context.ts
- src/nuxt.ts
Documented behaviour:
`testDir`, default value: '~~/test'
`fixture`, "a fixture directory (under `testDir`)", default value: 'fixture'
`rootDir`, default value: \<testDir>/\<fixture>
All works as expected if `setupTest` is called this way:
```js
setupTest({
fixture: 'some-fixture'
})
rootDir === '<process.cwd()>/test/fixture/some-fixture' // true
```
But it will not work with leading slash:
```js
setupTest({
fixture: '/some-fixture',
})
rootDir === '/some-fixture' // true
```
`path.resolve` is called inside `resolveRootDir` which returns `rootDir` value.
`path.join` instead of `path.resolve` does the right job.
By the way, `expectFileToBeGenerated` and `expectFileNotToBeGenerated` have the same issue. Calling `expectFileToBeGenerated('/index.html')` will not check if the file exists …
> fix: use `join` instead of `resolve` for paths related with `fixture` option

- src/context.ts
- src/server.ts
- src/setup.ts
- test/unit/server.test.ts
After migration to `listhen` (#129), server is not closed after tests run. Therefore, Jest throws “A worker process has failed to exit gracefully…” error. To recreate, try building the library and importing `setupTest` to a test from `dist`.
`listhen` has close on exit signal feature, but for some reason it does not work in Jest environment. The test below will throw the same error, because listener is not closing:
```js
import { listen } from 'listhen'
test('listhen', async () => {
await listen((req, res) => { res.end(req.url) })
// ...
})
```
The idea of auto closing server inspired me and I thought perhaps Nuxt could be also closed on exit signal. Did not manage to make this work and also found out that server is not closing. (I was trying out 'beforeExit' event too. No luck.)
Seems …
> fix: close server explicitly

- docs/content/en/api-reference/setup.md
- src/context.ts
- src/generate.ts
Perhaps it makes sense to remove `generateOptions` to improve typings.
`options.generate` was passed to generator instead of `options. generateOptions`, it was not possible to use it. That’s why this PR is only fixing typings.
Of course, it can be brought back later if there is a use case.
> fix(types): remove not used `generateOptions`

- docs/content/en/api-reference/setup.md
- src/context.ts
- src/nuxt.ts
- src/server.ts
- test/unit/__snapshots__/context.test.ts.snap
- test/unit/fixture.test.ts
- test/unit/server.test.ts
It would be also useful to have `randomPort` option. Motivation is similar to `randomBuildDir` #137
Current:
* test server is trying to listen on `config.server.port`, random port is a fall back
* it is not possible to choose explicitly which value should be used in a test
Proposed:
* server always listens on random port (predictable)
* if `randomPort: false` is set, custom port is used (explicit)
**Use case.** For example, a fixture could have `config.server.port` set. One test ignores that. Another test has `randomPort: false` set and tries to listen on that particular port. There is no need to have separate fixtures or any additional logic. Inspired by real use case nuxt-community/auth-module#868 (see test file).
**Breaking.** If this PR is merged, previous implicit behaviour gets …
> feat!: add `randomPort` option

- docs/content/en/api-reference/setup.md
- src/context.ts
- src/nuxt.ts
- src/utils.ts
- test/unit/__snapshots__/context.test.ts.snap
- test/unit/fixture.test.ts
- test/unit/utils.test.ts
It would be useful to have a possibility to disable random `buildDir` explicitly.
Current:
* `buildDir` is patched with random string by default, but it will be implicitly not patched if custom `buildDir` is set inside `nuxt.config` file or `config` overrides has `buildDir` value
* there is no possibility to disable random default
* there is no possibility to add random part for a custom `buildDir`
Proposed:
* `buildDir` is always randomised (predictable)
* random part will be disabled if `randomBuildDir: false` is set (explicit)
**Use case.** If testing an app, one would be able to build it using a `package.json` script and run tests with `build: false` option set inside `setupTest`. There is no need to build the app with each `setupTest`, this makes the tests suite run significantly …
> feat!: add `randomBuildDir` option

- package.json
- yarn.lock
* move babel dev deps required by `jest-preset.js` to dependencies: see #93
* upgrade all dependencies & dev dependencies: the `siroc` upgrade resolves #140 
* pin dev deps so they can be managed by @renovate-bot in future
Happy to close this or split PR up if different approach is preferred (cc: @pi0).
> chore: dependency clean up

- src/nuxt.ts
- src/utils.ts
- test/unit/fixture.test.ts
- test/unit/utils.test.ts
While rebasing #134, I though the Nuxt app validation could be simplified.
Currently: always three calls to the file system.
Proposed: just one `readdir` call and validation in memory. Array’s `.some()` should help to return early.
In some exotic case, `pages` could also be a file. It is possible to detect this using `Dirent`s, but perhaps that’s too much for this small library.
Validation logic is factored out to improve testability.
> refactor: improve nuxt app validation

- docs/content/en/api-reference/setup.md
Hi ! 
getting over the docs I find out a tiny typo error on "amount" spelling .
> docs: fix typo

- examples/app/app.vue
- examples/app/components/MyComponent.vue
- examples/app/package.json
- examples/app/types/component-props.ts
- pnpm-lock.yaml
- src/config.ts
resolves https://github.com/nuxt/test-utils/issues/237
The issue here is that we are 'leaking' vitest config into the node context which runs e2e tests. Do you think there's a better way to avoid this, and just use this config for the nuxt environment @antfu?
> fix: do not set `process.browser` globally

- src/core/nuxt.ts
The types for the `setup()` function provide a `buildDir` option, this isn't used.
```ts
const { resolve } = createResolver(import.meta.url)
await setup({
rootDir: resolve('../fixtures/basic'),
buildDir: resolve('./build'), // doesn't do anything
})
```
> fix: use `buildDir` option

- package.json
- pnpm-lock.yaml
- src/config.ts
- src/environments/vitest/index.ts
- src/environments/vitest/types.ts
- src/module.ts
- src/module/plugins/entry.ts
- src/module/plugins/mock.ts
- src/runtime/entry.ts
- src/runtime/nuxt-root.ts
- test/unit/mock-transform.spec.ts
This moves the Nuxt environment setup into `setupFiles` which will provide a more consistent approach in future (https://github.com/danielroe/nuxt-vitest/pull/290#issuecomment-1744345443).
I've separated out this refactor from the move to Vitest 0.34+ as the approach is backwards-compatible.
resolves https://github.com/nuxt/test-utils/issues/573
cc: @sheremet-va
> fix!: load nuxt app within `setupFiles`

- src/core/nuxt.ts
- src/core/setup/index.ts
- src/core/types.ts
Review this first: https://github.com/nuxt/test-utils/pull/596
Test build dirs will just keep stacking up. There is no logic in place to remove them.
This isn't ideal, especially when your IDE tries to index these files (even though they're ignored - phpstorm :angry:)
This PR includes a few important fixes:
- group test builds in a `test` directory so they can easily be cleaned up manually, this may be needed if a test fails/is force quit
- mark the build directory that's created as a side effect and clean it up once the tests are finished
> fix: teardown test build directories

- examples/app-vitest-full/components/WrapperTests.vue
- examples/app-vitest-full/nuxt.config.ts
- examples/app-vitest-full/tests/nuxt/index.spec.ts
closes https://github.com/nuxt/nuxt-vitest/pull/193
linked to https://github.com/nuxt/test-utils/issues/572
> test: add tests for events emitted from `defineModel`

- examples/app-vitest-full/vitest.config.ts
- src/config.ts
> fix(vitest-environment): normalise `setupFiles` to array before merge

- examples/i18n/app.vue
- examples/i18n/i18n.config.ts
- examples/i18n/test/index.spec.ts
https://github.com/nuxt/test-utils/pull/673
Thank you @sarayourfriend for catching this 😆 Must have been deleted accidentally at some point before merging this test fixture.
> test: update to actually use `$t`

- examples/app-vitest-full/components/LinkTests.vue
- examples/app-vitest-full/tests/nuxt/mount-suspended.spec.ts
- examples/app-vitest-full/tests/nuxt/render-suspended.spec.ts
- src/runtime-utils/components/RouterLink.ts
* Update RouterLink to make the `to` prop required (it's required in the actual RouterLink component https://github.com/vuejs/vue-router/blob/0395bd83feb79b3cba399e68f991885c986f70ec/src/components/link.js#L23)
* Get the href from the resolved route, rather than `props.to`
* Fixes https://github.com/nuxt/test-utils/issues/686
> fix(runtime-utils): RouterLink - use the correct href when props.to is object

- src/module/plugins/mock.ts
Hi :wave: 
This PR fix an issue on windows. In Windows running `pnpm test:examples` don't work. So this PR makes the importPath always added.
Would be nice to have multiple platform for the CI;
> fix: always append import when mocking

- examples/app-cucumber/app.vue
- examples/app-cucumber/cucumber.json
- examples/app-cucumber/nuxt.config.ts
- examples/app-cucumber/package.json
- examples/app-cucumber/test/acceptance/features/home/features/home.feature
- examples/app-cucumber/test/acceptance/features/playwright/step-definitions/playwright.given-steps.ts
- examples/app-cucumber/test/acceptance/features/support/hooks.ts
- examples/app-cucumber/tsconfig.json
- package.json
- pnpm-lock.yaml
- src/core/setup/cucumber.ts
- src/core/setup/index.ts
- src/core/types.ts
this adds a built-in `cucumber` test runner for e2e tests
resolves https://github.com/nuxt/test-utils/issues/697
> feat(e2e): add `cucumber` test runner

- .github/workflows/ci.yml
Caching the Playwright browsers is a concept which often leads to confusion, since yes, browsers can be cached, but they also rely on operating system dependencies, which can't be cached.
This might work for Chromium, since GitHub Action environments have all the OS dependencies already pre-installed for running Chromium, but for WebKit / Firefox this won't work (launch will yell with dependencies missing error).
So having this extra complexity for saving 1-5 seconds on a process (downloading the browsers) which only [takes 5 seconds](https://github.com/nuxt/test-utils/actions/runs/8303902994/job/22728801115#step:9:11) seems not worth it (restoring the cache takes a similar duration)
See also here: https://playwright.dev/docs/ci#caching-browsers
> ci: remove caching of Playwright browsers

- package.json
The `playwright.d.ts` is provided but not included in the `files`.
So, we would like to include it in `files`.
> fix: add `playwright.d.ts` into `files`

- package.json
- pnpm-lock.yaml
- src/core/server.ts
- src/core/types.ts
> feat(deps): upgrade `execa` to v9

- .github/workflows/ci.yml
- package.json
- patches/nuxt@3.11.2.patch
- pnpm-lock.yaml
https://github.com/nuxt/test-utils/pull/848
> ci: run test suite on windows

- examples/app-vitest-full/tests/nuxt/render-suspended.spec.ts
- src/runtime-utils/render.ts
After a lot of internal testing in my private project and seeing some similar opened issues about the context returned by setup was not being accessible in the component, I saw that there was a difference in the way how `mountSuspended` and `renderSuspended` were defined.
In `mountSuspended` things always worked, looking at the difference between the two I ended up arriving at the PR https://github.com/danielroe/nuxt-vitest/pull/391 which introduced a fix for this, but only on the mountSuspended function
It would be cool at some point to unify what is possible in these two functions. There is a lot of duplicated logic between  both
Fix: https://github.com/nuxt/test-utils/issues/722
> feat(runtime-utils): expose setup context from `renderSuspended` result

- examples/app-vitest-full/components/ExportDefaultComponent.vue
- examples/app-vitest-full/components/ExportDefaultReturnsRenderComponent.vue
- examples/app-vitest-full/components/ExportDefaultWithRenderComponent.vue
- examples/app-vitest-full/components/ExportDefineComponent.vue
- examples/app-vitest-full/tests/nuxt/mount-suspended.spec.ts
- src/runtime-utils/mount.ts
Use custom merge function via `createDefu` at `setProps()` to replace prop that has array type.
Because `defu()` concats array instead of overwrite in default behavior. ([Link](https://github.com/unjs/defu?tab=readme-ov-file#remarks)) 
> Will concat array values (if default property is defined)
Fix: #876
> fix(runtime-utils): `setProps` can replace array prop

- src/core/setup/index.ts
- src/core/types.ts
Hi,
I noticed that the nuxt server launched by the playwright fixture always uses the current environment variables without the option to overwrite them. So I exposed the already existing option to overwrite them from the startServer command into the playwright config. This way it's possible to define env variables to use during testing either globally or even overwrite them per test.
Example:
```ts
export default defineConfig<ConfigOptions>({
use: {
nuxt: {
rootDir: fileURLToPath(new URL(".", import.meta.url)),
env: {
// Overwrite backend url during tests. This way the .env can still contain the real one used during development.
NUXT_BACKEND_URL: "http://mocked-backend.example/api",
},
},
},
});
```
> feat(e2e): allow overwriting env variables in `setup`

- src/module.ts
An error message like this appears:
[1:39:59 PM]  ERROR  1:39:59 PM [vite] Pre-transform error: Failed to resolve import "/@vite-plugin-checker-runtime-entry" from "node_modules/nuxt/dist/app/entry.js". Does the file exist?
With a empty nuxt project and the following config:
```bash
npm i --save-dev @nuxt/test-utils vitest @vue/test-utils happy-dom playwright-core
npm i --save-dev @vitest/ui
npm i --save-dev vue-tsc typescript
```
```ts
export default defineNuxtConfig({
compatibilityDate: "2024-04-03",
devtools: { enabled: true },
modules: ["@nuxt/test-utils"],
typescript: {
typeCheck: true,
},
testUtils: {
startOnBoot: true,
},
})
```
See this reproduction link: https://stackblitz.com/edit/github-hxk7b6
> fix: avoid error message with tsc and nuxt test-utils

- stubs/vitest-environment-nuxt/package.json
A small change to ensure the `"license": "MIT"` is included in `stubs/vitest-environment-nuxt/package.json` - primarily done so that automated license scanning tools can look in the `package.json` and confirm the correct license to ensure a project doesn't accidentally use a potentially dangerous license (for closed source work).
An example of such a license finder can be found here: [LicenseFInder](https://github.com/pivotal/LicenseFinder/tree/master).
> chore: Add 'MIT' license to vitest-environment-nuxt package.json

- src/environments/vitest/index.ts
Removed the hardcoded window URL. Now it references an environment option for better configurability.
> fix(vitest-environment): respect custom url in setup

- examples/app-vitest-full/components/DirectiveComponent.vue
- examples/app-vitest-full/plugins/directive.ts
- examples/app-vitest-full/tests/nuxt/mount-suspended.spec.ts
- src/runtime-utils/mount.ts
resolves https://github.com/nuxt/test-utils/issues/959
- [ x] 👌 Enhancement (improving an existing functionality)
Custom vue directives, typically added through a nuxt plugin, are not available in the testing environment.
For example the following plugin defines a custom uppercase directive:
```
export default defineNuxtPlugin(({ vueApp }) => {
vueApp.directive('uppercase', {
mounted: (el, binding, node) => {
// ...impl code
},
})
})
```
However when running tests the below warning can be observed:
```
[Vue warn]: Failed to resolve directive: uppercase
at <MountSuspendedComponent >
at <MountSuspendedHelper>
at <Anonymous ref="VTU_COMPONENT" >
at <VTUROOT>
[Vue warn]: Failed to resolve directive: uppercase 
at <MountSuspendedComponent > 
at <MountSuspendedHelper> 
at <Anonymous …
```
> fix(runtime-utils): pass global `directives` to `mountSuspended`

- examples/app-vitest-full/pages/other/options-api.vue
- examples/app-vitest-full/tests/nuxt/mount-suspended.spec.ts
- examples/app-vitest-full/tests/nuxt/render-suspended.spec.ts
- src/runtime-utils/mount.ts
- src/runtime-utils/render.ts
fixes #961 
As described in #961, mountSuspended did not support the Options API data, computed, and methods, so we have fixed this to support them.
> fix(runtime-utils): support options api data, computed + methods

- src/core/context.ts
setting `NODE_ENV` is necessary when running a built nuxt server as it affects how dependencies are resolved - and even runtime behaviour (whether vue router logs errors, for example)
> fix(e2e): set `NODE_ENV` when running built server

- examples/app-vitest-full/components/TestButton.vue
- examples/app-vitest-full/pages/other/options-api.vue
- examples/app-vitest-full/tests/nuxt/mount-suspended.spec.ts
- examples/app-vitest-full/tests/nuxt/render-suspended.spec.ts
- src/runtime-utils/mount.ts
- src/runtime-utils/render.ts
As described in https://github.com/nuxt/test-utils/issues/967, `this` in Options API methods is undefined, using mountSuspended or renderSuspended.
I have fixed them.
- Before fix: testing fails https://github.com/nuxt/test-utils/actions/runs/11246366028/job/31268077316?pr=971
- After fix: testing succeeds 🙌
> fix(runtime-utils): bind this in options api methods

- examples/app-vitest-full/components/ComponentWithReservedProp.vue
- examples/app-vitest-full/tests/nuxt/mount-suspended.spec.ts
- src/runtime-utils/mount.ts
- src/runtime-utils/render.ts
resolves https://github.com/nuxt/test-utils/issues/684
This adds additional handling for props, including suppressing vue warnings when props are set initially, and accessing props from `renderContext.props` when there's a reserved keyword in props.
> fix(runtime-utils): handle reserved `props`

- src/environments/vitest/index.ts
This makes tests less noisy by suppressing the `<Suspense> is an experimental feature and its API will likely change.` warning that we're probably all too familiar with by this point. It's not relevant to _testing_ in any case, and it will still be visible in the browser when developing.
> fix(vitest-environment): suppress suspense warning

- examples/app-vitest-full/tests/nuxt/auto-import.spec.ts
- src/module/mock.ts
Fixes: https://github.com/nuxt/test-utils/issues/897
The `setInterval` overridden by Nuxt is auto-imported, so it can no longer be mocked with `useFakeTimers`. 
(`setInterval = window.setInterval`, but the previous state is retained.)
I think updating the documentation with a method like separating workspaces as shown below is one possible approach, but which would be more appropriate?
https://stackblitz.com/edit/github-agxb9y-slbn4d
> fix: remove `setInterval` from the presets

- dirs.js
resolves https://github.com/nuxt/test-utils/issues/1038
resolves https://github.com/nuxt/test-utils/issues/1050
It appears that 56122b7456953cf502b374117427beab1da35f1b caused a regression with 3.15 that can produce the following error. I suspect this is environment-specific. If it were widespread, I'd expect more people to be talking about it.
```
TypeError: The URL must be of scheme file
❯ ../node_modules/.pnpm/@nuxt+test-utils@3.15.1_@types+node@22.10.3_@vue+test-utils@2.4.6_happy-dom@15.11.7_magicast@_qhcyoib43mexeh3yv2rdveqtry/node_modules/@nuxt/test-utils/dirs.js:4:17
```
Making this change directly inside `node_modules` works for me, but @danielroe perhaps you can provide more context. If our goal is to simply resolve the `dist` directory, using `node:path` could be a safer way to …
> fix: use node:path to resolve dist directory

- examples/app-vitest-full/components/CustomComponent.vue
- examples/app-vitest-full/plugins/component.ts
- examples/app-vitest-full/tests/nuxt/mount-suspended.spec.ts
- src/runtime-utils/mount.ts
resolves #1080 
Custom vue components, typically added through a nuxt plugin, are not available in the testing environment.
sample:
```
export default defineNuxtPlugin(nuxtApp => {
nuxtApp.vueApp.component('font-awesome-icon', FontAwesomeIcon);
});
```
when running a test and mounting a component that uses `<font-awesome-icon>`:
```
[Vue warn]: Failed to resolve component: font-awesome-icon
```
> fix(runtime-utils): pass custom global components to mountSuspended

- examples/app-vitest-full/components/ExportDefaultComponent.vue
- examples/app-vitest-full/components/ExportDefaultReturnsRenderComponent.vue
- examples/app-vitest-full/components/ExportDefaultWithRenderComponent.vue
- examples/app-vitest-full/components/ExportDefineComponent.vue
- examples/app-vitest-full/tests/nuxt/mount-suspended.spec.ts
- examples/app-vitest-full/tests/nuxt/render-suspended.spec.ts
- src/runtime-utils/mount.ts
Fixes: https://github.com/nuxt/test-utils/issues/1072
In `defu`, the first argument takes precedence, so it is not overwritten. 
With this fix, props can now be overwritten just like in `mount`.
> fix: overwrite object props in the same way as `mount`

- examples/app-vitest-full/tests/nuxt/mount-suspended.spec.ts
- src/runtime-utils/mount.ts
ref: https://github.com/nuxt/test-utils/pull/1078
There were cases where `setProps` could not overwrite when `defu` was used. 
Therefore, the merging of props will no longer use `defu`.
> fix(runtim-utils): do not use `defu` for merging

- examples/app-vitest-full/components/ExportDefaultComponent.vue
- examples/app-vitest-full/tests/nuxt/mount-suspended.spec.ts
- src/runtime-utils/mount.ts
Fixes: https://github.com/nuxt/test-utils/issues/1064
When using `mountSuspended`, `wrapper.props` returns the props of the wrapped component instead of the specified component. 
To address this, proxy `wrapper.props` so that it returns the props of the `MountSuspendedComponent`.
> fix(runtime-utils): proxy wrapper props

- examples/app-vitest-full/components/ComponentWithAttrs.vue
- examples/app-vitest-full/tests/nuxt/mount-suspended.spec.ts
- examples/app-vitest-full/tests/nuxt/render-suspended.spec.ts
- src/runtime-utils/mount.ts
- src/runtime-utils/render.ts
Resolves #1092 
Fixes an issue where `$attrs`  are undefined when mounting a component using `mountSuspended` .
> fix(runtime-utils): define `$attrs` in component render context

- examples/app-vitest-full/components/WrapperElement.vue
- examples/app-vitest-full/tests/nuxt/mount-suspended.spec.ts
- src/runtime-utils/mount.ts
resolves: https://github.com/nuxt/test-utils/issues/1091
`wrapper.element` returned by `mountSuspended` returns the element of `NuxtRoot`, so use a proxy to return the element of the target component.
> fix: add proxy `wrapper.element`

- examples/app-vitest-full/tests/nuxt/mount-suspended.spec.ts
- src/runtime-utils/mount.ts
Resolved #572
With the change to resolve #572 the internal emit function for the component was changed to use the root component so that emits can be picked up by vitest.
This had the side-effect of breaking user-passed event listeners as props to the component:
```js
const component = await mountSuspended(MyComponent, {
props: {
'onUpdate:modelValue': async e => component.setProps({ modelValue: e }),
},
})
```
To resolve this I changed the internal component emit to call both the original emit and the root component emit.
I've also added a new unit test for this case.
> fix(runtime-utils): ensure event listeners props are called

- src/environments/vitest/index.ts
resolves https://github.com/nuxt/test-utils/issues/1212
I'd advise against using a custom baseURL in testing but this respects it if provided.
> fix(vitest-environment): respect custom `app.baseURL` in manifest path

- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/reproduire/needs-reproduction.md
- README.md
* https://github.com/nuxt/nuxt.com/issues/1841
This changes the URLs used in the markdown files and templates by removing trailing slashes.
This is actually a 'fix' for the link to the module authors docs page, which will show a 404 not found due to the trailing slash (tracking here https://github.com/nuxt/nuxt.com/issues/1841), until the underlying issue is resolved we can at least make sure the link works as expected 💪
> docs: consistent URL formatting

- .github/workflows/ci.yml
- build.config.ts
- examples/app-bun/app.vue
- examples/app-bun/nuxt.config.ts
- examples/app-bun/package.json
- examples/app-bun/test/browser.e2e.spec.ts
- examples/app-bun/test/dev.e2e.spec.ts
- examples/app-bun/test/server.e2e.spec.ts
- examples/app-bun/tsconfig.json
- package.json
- pnpm-lock.yaml
- src/core/context.ts
- src/core/setup/bun.ts
- src/core/setup/index.ts
- src/core/types.ts
- tsconfig.json
resolves https://github.com/nuxt/test-utils/issues/1254
this adds support for the bun test runner in e2e tests. it is auto-detected if used
> feat(e2e): add support for bun test runner

- examples/app-vitest-browser/app.vue
- examples/app-vitest-browser/components/MyCounter.vue
- examples/app-vitest-browser/nuxt.config.ts
- examples/app-vitest-browser/package.json
- examples/app-vitest-browser/test/component.test.ts
- examples/app-vitest-browser/tsconfig.json
- examples/app-vitest-browser/vitest.config.ts
- pnpm-lock.yaml
- src/config.ts
Resolves #1106
There was no example for Vitest Browser Mode. In order to get it working, I created an example, and then I had to make two code changes.
* Changing the setup files from resolving to "entry.ts" vs "entry"  may be due to a file path resolution issue?
* Removing the `[process.env.NODE_ENV]` definition caused the `process` is not defined error to go away.
> feat(config): support vitest browser mode

- examples/app-vitest-full/vitest.config.ts
- examples/app-vitest-workspace/nuxt.config.ts
- examples/app-vitest-workspace/package.json
- examples/app-vitest-workspace/test/app.nuxt.spec.ts
- examples/app-vitest-workspace/test/index.unit.spec.ts
- examples/app-vitest-workspace/tsconfig.json
- examples/app-vitest-workspace/vitest.config.ts
- examples/app-vitest-workspace/vitest.workspace.ts
- pnpm-lock.yaml
- src/config.ts
- src/module.ts
closes https://github.com/nuxt/test-utils/pull/1124
resolves https://github.com/nuxt/test-utils/issues/1123
this is the beginning of moving to vitest workspaces
> feat(config): support vitest workspaces with `defineVitestProject`

- examples/app-vitest-browser/components/MyCounter.vue
- examples/app-vitest-browser/test/component.test.ts
- examples/app-vitest-browser/test/mount-suspended.spec.ts
- src/config.ts
- src/environments/vitest/index.ts
- src/runtime/browser-entry.ts
- src/runtime/entry.ts
- src/runtime/shared/environment.ts
- src/runtime/shared/nuxt.ts
resolves https://github.com/nuxt/test-utils/issues/1283
This adds support for using the Nuxt environment in browser testing mode! (You need to explicitly set `environment: 'nuxt'` along with using the browser environment for this to work.
> feat(config): add nuxt environment browser-testing support

- build.config.ts
- package.json
- pnpm-lock.yaml
- src/module.ts
Currently test/utils has an explicit dependency on vite, as we need to respect the algo for merging vite configuration. But that does unduly bind a particular version of ntu to a certain version of vite (and therefore, perhaps, nuxt).
with the upcoming update to vite v7, this seems an appropriate time to import vite dynamically as-needed, respecting the version of the package that an end user has installed.
> fix(module): use user `vite` version to merge config

- examples/module/test/dot-config.test.ts
- examples/module/test/fixtures/dot-config/.config/nuxt.ts
- examples/module/test/fixtures/dot-config/app.vue
- examples/module/test/fixtures/dot-config/package.json
- src/e2e/nuxt.ts
Resolves #893
Some people are using the `.config` folder alternative for projects with many configuration files, and since `c12` from `unjs` and `nuxt` itself support `.config` folder would be nice to be able run tests using this alternative :)
Added support for detecting Nuxt apps that use config files inside the `.config` folder. I hardcoded the possible resolvable configs following the same pattern as the existing for default config files. No need to set `coonfigFile` option
Also added a `dot-config` test fixture in `examples/module/test/fixtures`
> fix(e2e): detect nuxt config files in `.config` folder

- examples/app-vitest-full/tests/nuxt/mount-suspended.spec.ts
- src/runtime-utils/mount.ts
resolves #1404
Currently, `vm` in `mountSuspended()` does not automatically unwrap refs, which is inconsistent with vue/test-utils:
```typescript
// Current behavior (inconsistent)
const component = await mountSuspended(SomeComponent)
console.log(component.vm.someRef) // Returns ref object, not the value
console.log(component.vm.someRef.value) // Need to manually access .value
// Expected behavior (vue/test-utils)
const wrapper = mount(SomeComponent)
console.log(wrapper.vm.someRef) // Returns unwrapped value
```
`wrapper.vm` should automatically unwrap refs to match vue/test-utils:
```typescript
const component = await mountSuspended(SomeComponent)
expect(component.vm.someRef).toBe('thing') // Should work directly
component.vm.someRef = 'new thing' // Should update ref.value …
```
> feat: Add automatic ref unwrapping for wrapper.vm
